//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DueDate { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime Changed { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
